export const icons = [
  { filename: "wi-barometer.svg", name: "Barometer" },
  { filename: "wi-celsius.svg", name: "Celsius" },
  { filename: "wi-cloud-down.svg", name: "Cloud Down" },
  { filename: "wi-cloud-refresh.svg", name: "Cloud Refresh" },
  { filename: "wi-cloud-up.svg", name: "Cloud Up" },
  { filename: "wi-cloud.svg", name: "Cloud" },
  { filename: "wi-cloudy-gusts.svg", name: "Cloudy Gusts" },
  { filename: "wi-cloudy-windy.svg", name: "Cloudy Windy" },
  { filename: "wi-cloudy.svg", name: "Cloudy" },
  { filename: "wi-day-cloudy-gusts.svg", name: "Day Cloudy Gusts" },
  { filename: "wi-day-cloudy-high.svg", name: "Day Cloudy High" },
  { filename: "wi-day-cloudy-windy.svg", name: "Day Cloudy Windy" },
  { filename: "wi-day-cloudy.svg", name: "Day Cloudy" },
  { filename: "wi-day-fog.svg", name: "Day Fog" },
  { filename: "wi-day-hail.svg", name: "Day Hail" },
  { filename: "wi-day-haze.svg", name: "Day Haze" },
  { filename: "wi-day-light-wind.svg", name: "Day Light Wind" },
  { filename: "wi-day-lightning.svg", name: "Day Lightning" },
  { filename: "wi-day-rain-mix.svg", name: "Day Rain Mix" },
  { filename: "wi-day-rain-wind.svg", name: "Day Rain Wind" },
  { filename: "wi-day-rain.svg", name: "Day Rain" },
  { filename: "wi-day-showers.svg", name: "Day Showers" },
  { filename: "wi-day-sleet-storm.svg", name: "Day Sleet Storm" },
  { filename: "wi-day-sleet.svg", name: "Day Sleet" },
  { filename: "wi-day-snow-thunderstorm.svg", name: "Day Snow Thunderstorm" },
  { filename: "wi-day-snow-wind.svg", name: "Day Snow Wind" },
  { filename: "wi-day-snow.svg", name: "Day Snow" },
  { filename: "wi-day-sprinkle.svg", name: "Day Sprinkle" },
  { filename: "wi-day-storm-showers.svg", name: "Day Storm Showers" },
  { filename: "wi-day-sunny-overcast.svg", name: "Day Sunny Overcast" },
  { filename: "wi-day-sunny.svg", name: "Day Sunny" },
  { filename: "wi-day-thunderstorm.svg", name: "Day Thunderstorm" },
  { filename: "wi-day-windy.svg", name: "Day Windy" },
  { filename: "wi-degrees.svg", name: "Degrees" },
  { filename: "wi-direction-down-left.svg", name: "Direction Down Left" },
  { filename: "wi-direction-down-right.svg", name: "Direction Down Right" },
  { filename: "wi-direction-down.svg", name: "Direction Down" },
  { filename: "wi-direction-left.svg", name: "Direction Left" },
  { filename: "wi-direction-right.svg", name: "Direction Right" },
  { filename: "wi-direction-up-left.svg", name: "Direction Up Left" },
  { filename: "wi-direction-up-right.svg", name: "Direction Up Right" },
  { filename: "wi-direction-up.svg", name: "Direction Up" },
  { filename: "wi-dust.svg", name: "Dust" },
  { filename: "wi-earthquake.svg", name: "Earthquake" },
  { filename: "wi-fahrenheit.svg", name: "Fahrenheit" },
  { filename: "wi-fire.svg", name: "Fire" },
  { filename: "wi-flood.svg", name: "Flood" },
  { filename: "wi-fog.svg", name: "Fog" },
  { filename: "wi-gale-warning.svg", name: "Gale Warning" },
  { filename: "wi-hail.svg", name: "Hail" },
  { filename: "wi-horizon-alt.svg", name: "Horizon Alt" },
  { filename: "wi-horizon.svg", name: "Horizon" },
  { filename: "wi-hot.svg", name: "Hot" },
  { filename: "wi-humidity.svg", name: "Humidity" },
  { filename: "wi-hurricane-warning.svg", name: "Hurricane Warning" },
  { filename: "wi-hurricane.svg", name: "Hurricane" },
  { filename: "wi-lightning.svg", name: "Lightning" },
  { filename: "wi-lunar-eclipse.svg", name: "Lunar Eclipse" },
  { filename: "wi-meteor.svg", name: "Meteor" },
  { filename: "wi-moon-alt-first-quarter.svg", name: "Moon Alt First Quarter" },
  { filename: "wi-moon-alt-full.svg", name: "Moon Alt Full" },
  { filename: "wi-moon-alt-new.svg", name: "Moon Alt New" },
  { filename: "wi-moon-alt-third-quarter.svg", name: "Moon Alt Third Quarter" },
  { filename: "wi-moon-first-quarter.svg", name: "Moon First Quarter" },
  { filename: "wi-moon-full.svg", name: "Moon Full" },
  { filename: "wi-moon-new.svg", name: "Moon New" },
  { filename: "wi-moon-third-quarter.svg", name: "Moon Third Quarter" },
  { filename: "wi-moon-waning-crescent-1.svg", name: "Moon Waning Crescent 1" },
  { filename: "wi-moon-waning-crescent-2.svg", name: "Moon Waning Crescent 2" },
  { filename: "wi-moon-waning-crescent-3.svg", name: "Moon Waning Crescent 3" },
  { filename: "wi-moon-waning-crescent-4.svg", name: "Moon Waning Crescent 4" },
  { filename: "wi-moon-waning-crescent-5.svg", name: "Moon Waning Crescent 5" },
  { filename: "wi-moon-waning-crescent-6.svg", name: "Moon Waning Crescent 6" },
  { filename: "wi-moon-waxing-6.svg", name: "Moon Waxing 6" },
  { filename: "wi-moonrise.svg", name: "Moonrise" },
  { filename: "wi-moonset.svg", name: "Moonset" },
  { filename: "wi-na.svg", name: "NA" },
  { filename: "wi-night-alt-cloudy-gusts.svg", name: "Night Alt Cloudy Gusts" },
  { filename: "wi-night-alt-cloudy-high.svg", name: "Night Alt Cloudy High" },
  { filename: "wi-night-alt-cloudy-windy.svg", name: "Night Alt Cloudy Windy" },
  { filename: "wi-night-alt-cloudy.svg", name: "Night Alt Cloudy" },
  { filename: "wi-night-alt-hail.svg", name: "Night Alt Hail" },
  { filename: "wi-night-alt-lightning.svg", name: "Night Alt Lightning" },
  { filename: "wi-night-alt-rain-mix.svg", name: "Night Alt Rain Mix" },
  { filename: "wi-night-alt-rain-wind.svg", name: "Night Alt Rain Wind" },
  { filename: "wi-night-alt-rain.svg", name: "Night Alt Rain" },
  { filename: "wi-night-alt-showers.svg", name: "Night Alt Showers" },
  { filename: "wi-night-alt-sleet-storm.svg", name: "Night Alt Sleet Storm" },
  { filename: "wi-night-alt-sleet.svg", name: "Night Alt Sleet" },
  {
    filename: "wi-night-alt-snow-thunderstorm.svg",
    name: "Night Alt Snow Thunderstorm",
  },
  { filename: "wi-night-alt-snow-wind.svg", name: "Night Alt Snow Wind" },
  { filename: "wi-night-alt-snow.svg", name: "Night Alt Snow" },
  { filename: "wi-night-alt-sprinkle.svg", name: "Night Alt Sprinkle" },
  {
    filename: "wi-night-alt-storm-showers.svg",
    name: "Night Alt Storm Showers",
  },
  { filename: "wi-night-alt-thunderstorm.svg", name: "Night Alt Thunderstorm" },
  { filename: "wi-night-clear.svg", name: "Night Clear" },
  { filename: "wi-night-cloudy-gusts.svg", name: "Night Cloudy Gusts" },
  { filename: "wi-night-cloudy-high.svg", name: "Night Cloudy High" },
  { filename: "wi-night-cloudy-windy.svg", name: "Night Cloudy Windy" },
  { filename: "wi-night-cloudy.svg", name: "Night Cloudy" },
  { filename: "wi-night-fog.svg", name: "Night Fog" },
  { filename: "wi-night-hail.svg", name: "Night Hail" },
  { filename: "wi-night-lightning.svg", name: "Night Lightning" },
  { filename: "wi-night-partly-cloudy.svg", name: "Night Partly Cloudy" },
  { filename: "wi-night-rain-mix.svg", name: "Night Rain Mix" },
  { filename: "wi-night-rain-wind.svg", name: "Night Rain Wind" },
  { filename: "wi-night-rain.svg", name: "Night Rain" },
  { filename: "wi-night-showers.svg", name: "Night Showers" },
  { filename: "wi-night-sleet-storm.svg", name: "Night Sleet Storm" },
  { filename: "wi-night-sleet.svg", name: "Night Sleet" },
  {
    filename: "wi-night-snow-thunderstorm.svg",
    name: "Night Snow Thunderstorm",
  },
  { filename: "wi-night-snow-wind.svg", name: "Night Snow Wind" },
  { filename: "wi-night-snow.svg", name: "Night Snow" },
  { filename: "wi-night-sprinkle.svg", name: "Night Sprinkle" },
  { filename: "wi-night-storm-showers.svg", name: "Night Storm Showers" },
  { filename: "wi-night-thunderstorm.svg", name: "Night Thunderstorm" },
  { filename: "wi-rain-mix.svg", name: "Rain Mix" },
  { filename: "wi-rain-wind.svg", name: "Rain Wind" },
  { filename: "wi-rain.svg", name: "Rain" },
  { filename: "wi-raindrop.svg", name: "Raindrop" },
  { filename: "wi-raindrops.svg", name: "Raindrops" },
  { filename: "wi-refresh-alt.svg", name: "Refresh Alt" },
  { filename: "wi-refresh.svg", name: "Refresh" },
  { filename: "wi-sandstorm.svg", name: "Sandstorm" },
  { filename: "wi-showers.svg", name: "Showers" },
  { filename: "wi-sleet.svg", name: "Sleet" },
  { filename: "wi-small-craft-advisory.svg", name: "Small Craft Advisory" },
  { filename: "wi-smog.svg", name: "Smog" },
  { filename: "wi-smoke.svg", name: "Smoke" },
  { filename: "wi-snow-wind.svg", name: "Snow Wind" },
  { filename: "wi-snow.svg", name: "Snow" },
  { filename: "wi-snowflake-cold.svg", name: "Snowflake Cold" },
  { filename: "wi-solar-eclipse.svg", name: "Solar Eclipse" },
  { filename: "wi-sprinkle.svg", name: "Sprinkle" },
  { filename: "wi-stars.svg", name: "Stars" },
  { filename: "wi-storm-showers.svg", name: "Storm Showers" },
  { filename: "wi-storm-warning.svg", name: "Storm Warning" },
  { filename: "wi-strong-wind.svg", name: "Strong Wind" },
  { filename: "wi-sunrise.svg", name: "Sunrise" },
  { filename: "wi-sunset.svg", name: "Sunset" },
  { filename: "wi-thermometer-exterior.svg", name: "Thermometer Exterior" },
  { filename: "wi-thermometer-internal.svg", name: "Thermometer Internal" },
  { filename: "wi-thermometer.svg", name: "Thermometer" },
  { filename: "wi-thunderstorm.svg", name: "Thunderstorm" },
  { filename: "wi-time-1.svg", name: "Time 1" },
  { filename: "wi-time-10.svg", name: "Time 10" },
  { filename: "wi-time-11.svg", name: "Time 11" },
  { filename: "wi-time-12.svg", name: "Time 12" },
  { filename: "wi-time-2.svg", name: "Time 2" },
  { filename: "wi-time-3.svg", name: "Time 3" },
  { filename: "wi-time-4.svg", name: "Time 4" },
  { filename: "wi-time-5.svg", name: "Time 5" },
  { filename: "wi-time-6.svg", name: "Time 6" },
  { filename: "wi-time-7.svg", name: "Time 7" },
  { filename: "wi-time-8.svg", name: "Time 8" },
  { filename: "wi-time-9.svg", name: "Time 9" },
  { filename: "wi-tornado.svg", name: "Tornado" },
  { filename: "wi-train.svg", name: "Train" },
  { filename: "wi-tsunami.svg", name: "Tsunami" },
  { filename: "wi-umbrella.svg", name: "Umbrella" },
  { filename: "wi-volcano.svg", name: "Volcano" },
  { filename: "wi-wind-beaufort-0.svg", name: "Wind Beaufort 0" },
  { filename: "wi-wind-beaufort-1.svg", name: "Wind Beaufort 1" },
  { filename: "wi-wind-beaufort-10.svg", name: "Wind Beaufort 10" },
  { filename: "wi-wind-beaufort-11.svg", name: "Wind Beaufort 11" },
  { filename: "wi-wind-beaufort-12.svg", name: "Wind Beaufort 12" },
  { filename: "wi-wind-beaufort-2.svg", name: "Wind Beaufort 2" },
  { filename: "wi-wind-beaufort-3.svg", name: "Wind Beaufort 3" },
  { filename: "wi-wind-beaufort-4.svg", name: "Wind Beaufort 4" },
  { filename: "wi-wind-beaufort-5.svg", name: "Wind Beaufort 5" },
  { filename: "wi-wind-beaufort-6.svg", name: "Wind Beaufort 6" },
  { filename: "wi-wind-beaufort-7.svg", name: "Wind Beaufort 7" },
  { filename: "wi-wind-beaufort-8.svg", name: "Wind Beaufort 8" },
  { filename: "wi-wind-beaufort-9.svg", name: "Wind Beaufort 9" },
  { filename: "wi-wind-deg.svg", name: "Wind Deg" },
  { filename: "wi-windy.svg", name: "Windy" },
];
