const weatherIcons = [
  {
    code: 0,
    description: "Clear sky",
    icon_day: "wi-day-sunny.svg",
    icon_night: "wi-night-clear.svg",
  },
  {
    code: 1,
    description: "Mainly clear",
    icon_day: "wi-day-cloudy.svg",
    icon_night: "wi-night-alt-partly-cloudy.svg",
  },
  {
    code: 2,
    description: "Partly cloudy",
    icon_day: "wi-day-cloudy-high.svg",
    icon_night: "wi-night-alt-cloudy-high.svg",
  },
  {
    code: 3,
    description: "Cloudy",
    icon_day: "wi-cloud.svg",
    icon_night: "wi-cloud.svg",
  },
  {
    code: 4,
    description: "Overcast",
    icon_day: "wi-cloud.svg",
    icon_night: "wi-night-cloudy.svg",
  },
  {
    code: 5,
    description: "Fog or mist",
    icon_day: "wi-day-fog.svg",
    icon_night: "wi-night-fog.svg",
  },
  {
    code: 6,
    description: "Very low cloud",
    icon_day: "wi-cloud-down.svg",
    icon_night: "wi-night-cloudy.svg",
  },
  {
    code: 7,
    description: "Low cloud",
    icon_day: "wi-cloud-refresh.svg",
    icon_night: "wi-night-cloudy-windy.svg",
  },
  {
    code: 8,
    description: "High cloud",
    icon_day: "wi-cloud-up.svg",
    icon_night: "wi-night-alt-cloudy-windy.svg",
  },
  {
    code: 9,
    description: "No significant cloud",
    icon_day: "wi-day-sunny.svg",
    icon_night: "wi-night-clear.svg",
  },
  {
    code: 10,
    description: "Light rain",
    icon_day: "wi-day-rain.svg",
    icon_night: "wi-night-rain.svg",
  },
  {
    code: 11,
    description: "Moderate rain",
    icon_day: "wi-day-showers.svg",
    icon_night: "wi-night-showers.svg",
  },
  {
    code: 12,
    description: "Heavy rain",
    icon_day: "wi-day-rain-mix.svg",
    icon_night: "wi-night-alt-rain-mix.svg",
  },
  {
    code: 13,
    description: "Light snow",
    icon_day: "wi-day-snow.svg",
    icon_night: "wi-night-snow.svg",
  },
  {
    code: 14,
    description: "Moderate snow",
    icon_day: "wi-day-snow-wind.svg",
    icon_night: "wi-night-snow-wind.svg",
  },
  {
    code: 15,
    description: "Heavy snow",
    icon_day: "wi-day-snow-wind.svg",
    icon_night: "wi-night-snow-wind.svg",
  },
  {
    code: 16,
    description: "Sleet or ice pellets",
    icon_day: "wi-day-sleet.svg",
    icon_night: "wi-night-alt-sleet.svg",
  },
  {
    code: 17,
    description: "Light sleet or ice pellets",
    icon_day: "wi-day-sleet.svg",
    icon_night: "wi-night-alt-sleet.svg",
  },
  {
    code: 18,
    description: "Moderate sleet or ice pellets",
    icon_day: "wi-day-sleet.svg",
    icon_night: "wi-night-alt-sleet.svg",
  },
  {
    code: 19,
    description: "Heavy sleet or ice pellets",
    icon_day: "wi-day-sleet.svg",
    icon_night: "wi-night-alt-sleet.svg",
  },
  {
    code: 20,
    description: "Drizzle",
    icon_day: "wi-day-sprinkle.svg",
    icon_night: "wi-night-sprinkle.svg",
  },

  {
    code: 21,
    description: "Freezing drizzle",
    icon_day: "wi-day-sleet.svg",
    icon_night: "wi-night-sleet.svg",
  },
  {
    code: 22,
    description: "Snow grains",
    icon_day: "wi-snowflake-cold.svg",
    icon_night: "wi-snowflake-cold.svg",
  },
  {
    code: 23,
    description: "Light snow showers",
    icon_day: "wi-day-snow.svg",
    icon_night: "wi-night-snow.svg",
  },
  {
    code: 24,
    description: "Moderate snow showers",
    icon_day: "wi-day-snow-wind.svg",
    icon_night: "wi-night-snow-wind.svg",
  },
  {
    code: 25,
    description: "Heavy snow showers",
    icon_day: "wi-day-snow-thunderstorm.svg",
    icon_night: "wi-night-snow-thunderstorm.svg",
  },
  {
    code: 26,
    description: "Light rain showers",
    icon_day: "wi-day-showers.svg",
    icon_night: "wi-night-showers.svg",
  },
  {
    code: 27,
    description: "Moderate rain showers",
    icon_day: "wi-day-rain-mix.svg",
    icon_night: "wi-night-rain-mix.svg",
  },
  {
    code: 28,
    description: "Heavy rain showers",
    icon_day: "wi-day-rain.svg",
    icon_night: "wi-night-rain.svg",
  },
  {
    code: 29,
    description: "Light thunderstorm",
    icon_day: "wi-day-thunderstorm.svg",
    icon_night: "wi-night-thunderstorm.svg",
  },
  {
    code: 30,
    description: "Moderate thunderstorm",
    icon_day: "wi-day-lightning.svg",
    icon_night: "wi-night-lightning.svg",
  },
  {
    code: 31,
    description: "Heavy thunderstorm",
    icon_day: "wi-day-storm-showers.svg",
    icon_night: "wi-night-storm-showers.svg",
  },
  {
    code: 32,
    description: "Thunderstorm with light hail",
    icon_day: "wi-day-sleet-storm.svg",
    icon_night: "wi-night-alt-sleet-storm.svg",
  },
  {
    code: 33,
    description: "Thunderstorm with moderate hail",
    icon_day: "wi-day-sleet-storm.svg",
    icon_night: "wi-night-alt-sleet-storm.svg",
  },
  {
    code: 34,
    description: "Thunderstorm with heavy hail",
    icon_day: "wi-day-sleet-storm.svg",
    icon_night: "wi-night-alt-sleet-storm.svg",
  },
  {
    code: 35,
    description: "Snow flurries",
    icon_day: "wi-snowflake-cold.svg",
    icon_night: "wi-snowflake-cold.svg",
  },
  {
    code: 36,
    description: "Snow showers with thunder",
    icon_day: "wi-day-snow-thunderstorm.svg",
    icon_night: "wi-night-snow-thunderstorm.svg",
  },
  {
    code: 37,
    description: "Snow showers with light thunder",
    icon_day: "wi-day-snow-thunderstorm.svg",
    icon_night: "wi-night-snow-thunderstorm.svg",
  },
  {
    code: 38,
    description: "Snow showers with moderate thunder",
    icon_day: "wi-day-snow-thunderstorm.svg",
    icon_night: "wi-night-snow-thunderstorm.svg",
  },
  {
    code: 39,
    description: "Snow showers with heavy thunder",
    icon_day: "wi-day-snow-thunderstorm.svg",
    icon_night: "wi-night-snow-thunderstorm.svg",
  },
  {
    code: 40,
    description: "Freezing rain",
    icon_day: "wi-day-sleet-storm.svg",
    icon_night: "wi-night-sleet-storm.svg",
  },

  {
    code: 41,
    description: "Hail",
    icon_day: "wi-day-hail.svg",
    icon_night: "wi-night-hail.svg",
  },
  {
    code: 42,
    description: "Blowing dust or sand",
    icon_day: "wi-sandstorm.svg",
    icon_night: "wi-sandstorm.svg",
  },
  {
    code: 43,
    description: "Blowing snow",
    icon_day: "wi-day-snow-wind.svg",
    icon_night: "wi-night-snow-wind.svg",
  },
  {
    code: 44,
    description: "Tornado or waterspout",
    icon_day: "wi-tornado.svg",
    icon_night: "wi-tornado.svg",
  },
  {
    code: 45,
    description: "Hurricane",
    icon_day: "wi-hurricane.svg",
    icon_night: "wi-hurricane.svg",
  },
  {
    code: 46,
    description: "Severe thunderstorm",
    icon_day: "wi-day-storm-showers.svg",
    icon_night: "wi-night-storm-showers.svg",
  },
  {
    code: 47,
    description: "Dust or sand",
    icon_day: "wi-dust.svg",
    icon_night: "wi-dust.svg",
  },
  {
    code: 48,
    description: "Dust storm",
    icon_day: "wi-sandstorm.svg",
    icon_night: "wi-sandstorm.svg",
  },
  {
    code: 49,
    description: "Snowstorm",
    icon_day: "wi-day-snow-thunderstorm.svg",
    icon_night: "wi-night-snow-thunderstorm.svg",
  },
  {
    code: 50,
    description: "Light winds",
    icon_day: "wi-day-light-wind.svg",
    icon_night: "wi-windy.svg",
  },
  {
    code: 51,
    description: "Moderate winds",
    icon_day: "wi-strong-wind.svg",
    icon_night: "wi-strong-wind.svg",
  },
  {
    code: 52,
    description: "Strong winds",
    icon_day: "wi-small-craft-advisory.svg",
    icon_night: "wi-small-craft-advisory.svg",
  },
  {
    code: 53,
    description: "Gale force winds",
    icon_day: "wi-gale-warning.svg",
    icon_night: "wi-gale-warning.svg",
  },
  {
    code: 54,
    description: "Storm force winds",
    icon_day: "wi-storm-warning.svg",
    icon_night: "wi-storm-warning.svg",
  },
  {
    code: 55,
    description: "Hurricane force winds",
    icon_day: "wi-hurricane-warning.svg",
    icon_night: "wi-hurricane-warning.svg",
  },
  {
    code: 56,
    description: "High winds (gusts)",
    icon_day: "wi-day-cloudy-gusts.svg",
    icon_night: "wi-night-cloudy-gusts.svg",
  },
  {
    code: 57,
    description: "Squall or gust front",
    icon_day: "wi-day-cloudy-gusts.svg",
    icon_night: "wi-night-cloudy-gusts.svg",
  },
  {
    code: 58,
    description: "Wind shear",
    icon_day: "wi-day-cloudy-gusts.svg",
    icon_night: "wi-night-cloudy-gusts.svg",
  },
  {
    code: 59,
    description: "Calm conditions",
    icon_day: "wi-day-sunny.svg",
    icon_night: "wi-night-clear.svg",
  },
  {
    code: 60,
    description: "Freezing fog",
    icon_day: "wi-day-fog.svg",
    icon_night: "wi-night-fog.svg",
  },
  {
    code: 61,
    description: "Frost",
    icon_day: "wi-snowflake-cold.svg",
    icon_night: "wi-snowflake-cold.svg",
  },
  {
    code: 62,
    description: "Ice",
    icon_day: "wi-snow-wind.svg",
    icon_night: "wi-snow-wind.svg",
  },
  {
    code: 63,
    description: "Freezing fog with visibility under 100m",
    icon_day: "wi-day-fog.svg",
    icon_night: "wi-night-fog.svg",
  },
  {
    code: 64,
    description: "Temperature drop (significant)",
    icon_day: "wi-celsius.svg",
    icon_night: "wi-celsius.svg",
  },
  {
    code: 65,
    description: "Low visibility (<1 km)",
    icon_day: "wi-fog.svg",
    icon_night: "wi-fog.svg",
  },
  {
    code: 66,
    description: "Fog or mist with visibility 1-5 km",
    icon_day: "wi-day-fog.svg",
    icon_night: "wi-night-fog.svg",
  },
  {
    code: 67,
    description: "Dense fog with visibility under 100 meters",
    icon_day: "wi-day-fog.svg",
    icon_night: "wi-night-fog.svg",
  },
  {
    code: 68,
    description: "Light fog or haze",
    icon_day: "wi-day-haze.svg",
    icon_night: "wi-fog.svg",
  },
  {
    code: 69,
    description: "Dust haze",
    icon_day: "wi-dust.svg",
    icon_night: "wi-dust.svg",
  },
  {
    code: 70,
    description: "Rapid decrease in pressure",
    icon_day: "wi-barometer.svg",
    icon_night: "wi-barometer.svg",
  },
  {
    code: 71,
    description: "Rapid increase in pressure",
    icon_day: "wi-barometer.svg",
    icon_night: "wi-barometer.svg",
  },
  {
    code: 72,
    description: "Pressure rises slowly",
    icon_day: "wi-barometer.svg",
    icon_night: "wi-barometer.svg",
  },
  {
    code: 73,
    description: "Pressure falls slowly",
    icon_day: "wi-barometer.svg",
    icon_night: "wi-barometer.svg",
  },
  {
    code: 74,
    description: "Average pressure level",
    icon_day: "wi-barometer.svg",
    icon_night: "wi-barometer.svg",
  },
  {
    code: 75,
    description: "High atmospheric pressure",
    icon_day: "wi-barometer.svg",
    icon_night: "wi-barometer.svg",
  },
  {
    code: 76,
    description: "Low atmospheric pressure",
    icon_day: "wi-barometer.svg",
    icon_night: "wi-barometer.svg",
  },
  {
    code: 77,
    description: "Slight pressure change",
    icon_day: "wi-barometer.svg",
    icon_night: "wi-barometer.svg",
  },
  {
    code: 78,
    description: "Severe pressure change",
    icon_day: "wi-barometer.svg",
    icon_night: "wi-barometer.svg",
  },
  {
    code: 79,
    description: "Normal pressure conditions",
    icon_day: "wi-barometer.svg",
    icon_night: "wi-barometer.svg",
  },
  {
    code: 80,
    description: "Severe weather warning",
    icon_day: "wi-gale-warning.svg",
    icon_night: "wi-gale-warning.svg",
  },
  {
    code: 81,
    description: "Severe thunderstorm warning",
    icon_day: "wi-day-thunderstorm.svg",
    icon_night: "wi-night-thunderstorm.svg",
  },
  {
    code: 82,
    description: "Severe windstorm",
    icon_day: "wi-day-windy.svg",
    icon_night: "wi-night-cloudy-windy.svg",
  },
  {
    code: 83,
    description: "Ice storm warning",
    icon_day: "wi-day-sleet-storm.svg",
    icon_night: "wi-night-alt-sleet-storm.svg",
  },
  {
    code: 84,
    description: "Tornado warning",
    icon_day: "wi-tornado.svg",
    icon_night: "wi-tornado.svg",
  },
  {
    code: 85,
    description: "Flood warning",
    icon_day: "wi-flood.svg",
    icon_night: "wi-flood.svg",
  },
  {
    code: 86,
    description: "Heat warning",
    icon_day: "wi-hot.svg",
    icon_night: "wi-hot.svg",
  },
  {
    code: 87,
    description: "Cold wave warning",
    icon_day: "wi-snowflake-cold.svg",
    icon_night: "wi-snowflake-cold.svg",
  },
  {
    code: 88,
    description: "Tropical storm warning",
    icon_day: "wi-hurricane-warning.svg",
    icon_night: "wi-hurricane-warning.svg",
  },
  {
    code: 89,
    description: "Winter storm warning",
    icon_day: "wi-day-snow-wind.svg",
    icon_night: "wi-night-snow-wind.svg",
  },
  {
    code: 90,
    description: "Severe lightning",
    icon_day: "wi-day-lightning.svg",
    icon_night: "wi-night-lightning.svg",
  },
  {
    code: 91,
    description: "Dust storm warning",
    icon_day: "wi-dust.svg",
    icon_night: "wi-dust.svg",
  },
  {
    code: 92,
    description: "High surf warning",
    icon_day: "wi-tsunami.svg",
    icon_night: "wi-tsunami.svg",
  },
  {
    code: 93,
    description: "Avalanche warning",
    icon_day: "wi-snow-wind.svg",
    icon_night: "wi-snow-wind.svg",
  },
  {
    code: 94,
    description: "Tornado watch",
    icon_day: "wi-tornado.svg",
    icon_night: "wi-tornado.svg",
  },
  {
    code: 95,
    description: "Flash flood watch",
    icon_day: "wi-flood.svg",
    icon_night: "wi-flood.svg",
  },
  {
    code: 96,
    description: "High wind watch",
    icon_day: "wi-day-windy.svg",
    icon_night: "wi-night-cloudy-windy.svg",
  },
  {
    code: 97,
    description: "Heat wave",
    icon_day: "wi-hot.svg",
    icon_night: "wi-hot.svg",
  },
  {
    code: 98,
    description: "Extreme cold",
    icon_day: "wi-snowflake-cold.svg",
    icon_night: "wi-snowflake-cold.svg",
  },
  {
    code: 99,
    description: "No significant weather",
    icon_day: "wi-day-sunny.svg",
    icon_night: "wi-night-clear.svg",
  },
];

export default weatherIcons;
